services:
  testmind-api:
    build: .
    container_name: testmind-api
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - .:/app  
      - ./data/uploads:/app/data/uploads
      - ./scripts:/app/scripts
      - ./data/exports:/app/data/exports
  
  db:
    image: postgres:15
    container_name: testmind-db
    restart: always
    environment:
      POSTGRES_USER: franperci
      POSTGRES_PASSWORD: mansanita15
      POSTGRES_DB: TestMind
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - db

volumes:
  postgres_data:
